import type { Metadata } from "next";
import "antd-mobile/bundle/css-vars-patch.css"
import "antd-mobile/bundle/style.css"
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Header />
        <div className="mainContainer">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
